# Generated by Django 4.2.11 on 2024-04-08 03:47

from django.db import migrations
import js_blog_app.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_blog_app', '0004_galeriadeimagenesblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenesblog',
            name='video',
            field=wagtail.fields.StreamField([('video', js_blog_app.models.VideoBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galeriadeimagenesblog',
            name='video_2',
            field=wagtail.fields.StreamField([('video', js_blog_app.models.VideoBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galeriadeimagenesblog',
            name='video_3',
            field=wagtail.fields.StreamField([('video', js_blog_app.models.VideoBlock())], blank=True, null=True),
        ),
    ]
