# Generated by Django 4.2.11 on 2024-05-26 21:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_blog_app', '0005_galeriadeimagenesblog_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='nombre_campana',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
