version: "3.3"

services:
  qnd30_app_stg:
    image: smartquail/qnd30app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/static
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/media
    networks:
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: POSTFIXDB
      POSTGRES_USER: sqadmindb
      POSTGRES_PASSWORD: smartquaildev1719pass
    ports:
      - "5432:5432"
    volumes:
      - smartquaildb_data-qnode12:/var/lib/postgresql/data/
    networks:
      - lansmartquail

  nginx:
    image: smartquail/qnd30_nginx:prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd30_app_stg
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/static
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/media
      - certbot-web_2:/vol/www
      - proxy-dhparams_2:/vol/proxy
      - letsencrypt_certs:/etc/letsencrypt/
    networks: 
      - lansmartquail

  postfix:
    image: smartquail/qnd30postfix:prod
    restart: always
    container_name: postfix
    env_file:
      - .env
    depends_on:
      - dovecot
      - smartquaildb
      - opendkim
    ports:
      - "25:25"    # SMTP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
    volumes:
      - postfix-spools:/var/spool/postfix/private/
      - mail:/var/mail  # Correo en /var/mail para Postfix y Dovecot
      - postfix-logs:/var/log
      - opendkim:/var/spool/postfix/opendkim
      - certbot-web_2:/vol/www
      - letsencrypt_certs:/etc/letsencrypt
    networks:
      - lansmartquail

  opendkim:
    image: smartquail/qnd30opendkim:prod
    expose: 
      - "8891"
    ports:
      - "8891:8891"
    container_name: opendkim
    restart: always
    volumes:
      - opendkim:/etc/opendkim/keys  # Claves DKIM
      - opendkim:/var/spool/postfix/opendkim  # Socket para Postfix
    networks:
      - lansmartquail

  dovecot:
    image: smartquail/qnd30dovecot:prod
    container_name: dovecot
    restart: always
    depends_on:
      - smartquaildb
    volumes:
      - dovecot:/etc/dovecot
      - mail:/var/mail  # Correo en /var/mail para Postfix y Dovecot
      - postfix-spools:/var/spool/postfix/private/
      - letsencrypt_certs:/etc/letsencrypt
      - certbot-web_2:/vol/www
    ports:
      - "143:143"   # IMAP
      - "110:110"   # POP3
      - "993:993"   # IMAPS (secure IMAP)
      - "995:995"   # POP3S (secure POP3)
    environment:
      - DOVECOT_USER=dovecot
      - DOVECOT_PASSWORD=A1T2J3C42024
    networks:
      - lansmartquail

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@mail.smartquail.io
      PGADMIN_DEFAULT_PASSWORD: sqdatabaseadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - smartquaildb
    networks:
      - lansmartquail

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot-web_2:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"
    networks:
      - lansmartquail

  postfixadmin:
    image: postfixadmin
    container_name: postfixadmin
    environment:
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: smartquaildb
      POSTFIXADMIN_DB_NAME: POSFIXDB
      POSTFIXADMIN_DB_USER: sqadmindb
      POSTFIXADMIN_DB_PASSWORD: smartquaildev1719pass
      POSTFIXADMIN_SETUP_PASSWORD: A1T2J3C42024
      POSTFIXADMIN_ADMIN_EMAIL: admin@juansilvaphoto.com
      POSTFIXADMIN_ADMIN_PASSWORD: A1T2J3C42024
    ports:
      - "8080:80"
    volumes:
      - postfixadmin_data:/var/www/html
    depends_on:
      - smartquaildb
    networks:
      - lansmartquail
    restart: unless-stopped

volumes:
  opendkim:
  certbot-web_2:
  proxy-dhparams_2:
  letsencrypt_certs:
  static-data-qnd30:
  smartquaildb_data-qnode12:
  postfix-spools:
  postfix-spools-lmtp:
  mail:
  postfix-logs:
  dovecot:
  postfixadmin_data:

networks:
  lansmartquail:
    driver: bridge
