version: "3.3"

services:
  qnd30_app_stg:
    image: smartquail/qnd30app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/static
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/media
    mem_limit: 2g              # Límite máximo de memoria
    mem_reservation: 1g        # Reserva mínima de memoria
    networks: 
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    command: -p 5432
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data-qnode12:/var/lib/postgresql/data/
    networks: 
      - lansmartquail

  nginx:
    image: smartquail/qnd30_nginx:prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd30_app_stg
    ports:
      - 80:80
      - 443:443  
    volumes:
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/static
      - static-data-qnd30:/qnd30app/qnd30_app_stg/qnd30_app_stg/media
      - certbot-web_2:/vol/www
      - proxy-dhparams_2:/vol/proxy
      - letsencrypt_certs:/etc/letsencrypt/
    networks: 
      - lansmartquail




volumes:
  certbot-web_2:
  proxy-dhparams_2:
  letsencrypt_certs:
  static-data-qnd30:
  smartquaildb_data-qnd30:
  smartquaildb_data-qnode12:

networks: 
   lansmartquail:
       driver: bridge